base: Move CaseInsensitiveCompare traits into the base namespace.
This should fix conflicts like:
2>d:\src\chromium_src2\src\base/string_util.h(480) : error C2904: 'CaseInsensitiveCompare' : name already used for a template in the current scope
2>        d:\src\chromium_src2\src\third_party\xulrunner-sdk\win\include\xpcom\nsStringAPI.h(1406) : see declaration of 'CaseInsensitiveCompare'

Reported-by: Jeff Timanus <twiz@google.com>

BUG=None
TEST=trybots

Review URL: http://codereview.chromium.org/4366001

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 07f1ceeabc0cf63ed8d7ae7aa8d1ff04dda02584