Revert of Use a C++11 feature in a single file, to discover if this works everywhere. (patchset #5 id:70001 of https://codereview.chromium.org/443483002/)
Reason for revert:
Breaks Arm compile of Chrome on ChromeOS.

http://build.chromium.org/p/chromiumos.chromium/builders/Daisy%20%28chromium%29/builds/1732

chromeos-chrome-39.0.2157.0_alpha-r1: In file included from threading/watchdog.cc:5:0:
chromeos-chrome-39.0.2157.0_alpha-r1: ../base/threading/watchdog.h:68:29: error: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [-Werror]
chromeos-chrome-39.0.2157.0_alpha-r1:      virtual void ThreadMain() OVERRIDE;

Original issue's description:
> Use a C++11 feature in a single file, to discover if this works everywhere.
>
> Similar to https://codereview.chromium.org/385743002 , but in a file
> that's also built in host targets. Depends on r#294584.
>
> If your bot can't deal with this, please let me know!
>
> BUG=none
>
> Committed: https://crrev.com/5928c2f978a43488a2f45fe7da1d91dfdba1d593
> Cr-Commit-Position: refs/heads/master@{#294687}

TBR=ajwong@chromium.org,thakis@chromium.org
NOTREECHECKS=true
NOTRY=true
BUG=none

Review URL: https://codereview.chromium.org/570083002

(cherry picked from commit 908d52405f9961fd87d3b65287ab50f67a1d7c1b)

Cr-Original-Commit-Position: refs/branch-heads/2159@{#2}
Cr-Original-Original-Commit-Position: refs/heads/master@{#294822}
Cr-Original-Branched-From: 7279fced4d4890c54ce2ac52879fa2bf2b471c0a-refs/heads/master@{#294791}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 20b852abf33a3929419dc305ab5806487c88ebe1