Revert 204293 "Remove WeakPtr<T>'s operator T*()"
broke linux chromeos compile:

chromeos-chrome-29.0.1530.0_alpha-r1: content/common/gpu/media/exynos_video_decode_accelerator.cc: In member function 'void content::ExynosVideoDecodeAccelerator::NotifyError(media::VideoDecodeAccelerator::Error)':
chromeos-chrome-29.0.1530.0_alpha-r1: content/common/gpu/media/exynos_video_decode_accelerator.cc:1894:14: error: could not convert '((content::ExynosVideoDecodeAccelerator*)this)->content::ExynosVideoDecodeAccelerator::client_' from 'base::WeakPtr<media::VideoDecodeAccelerator::Client>' to 'bool'
...more errors

> Remove WeakPtr<T>'s operator T*()
> 
> BUG=245942
> R=darin@chromium.org
> 
> Review URL: https://codereview.chromium.org/16267003

TBR=akalin@chromium.org

Review URL: https://codereview.chromium.org/16229012

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: f2c8b48b6571b9e31e6518ac571e96e9da2aa62b