file_util.h won't compile if UNIT_TEST and OS_WIN are defined.
src\base/file_util.h(524) : error C2664: 'GetNamedSecurityInfoW' : cannot convert parameter 1 from 'const wchar_t *' to 'LPWSTR'

BUG=none
TEST=none

Review URL: http://codereview.chromium.org/1582040

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 130e036f019117d3341c2a15d06e5004e32c9501