Revert 167808 - Get rid of use of CreateStringValue in chromeos/ directory.
Reverting because the patch makes clang build failing:
> chrome/browser/chromeos/cros/network_library.cc:380:26:error: C++98 requires an
> accessible copy constructor for class 'base::StringValue' when binding a
>  reference to a temporary; was private [-Werror,-Wbind-to-temporary-copy]
>    SetValueProperty(prop, base::StringValue(str));
etc.

BUG=160586


Review URL: https://chromiumcodereview.appspot.com/11363203

TBR=estade@chromium.org
Review URL: https://codereview.chromium.org/11369258

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: c8c3f37f7dc08aee5f9199aa00a3c36c5403d9c5