Revert 242270 "Fixes in base for [P]NaCl port of remoting client"
Somewhat speculative, to try and fix

chromeos-chrome-34.0.1755.0_alpha-r1:   armv7a-cros-linux-gnueabi-g++ -B/usr/x86_64-pc-linux-gnu/armv7a-cros-linux-gnueabi/binutils-bin/2.22-gold '-DV8_DEPRECATION_WARNINGS' '-D_FILE_OFFSET_BITS=64' '-DCHROMIUM_BUILD' '-DTOOLKIT_VIEWS=1' '-DUI_COMPOSITOR_IMAGE_TRANSPORT' '-DUSE_AURA=1' '-DUSE_ASH=1' '-DUSE_CAIRO=1' '-DUSE_CRAS=1' '-DUSE_GLIB=1' '-DUSE_DEFAULT_RENDER_THEME=1' '-DUSE_NSS=1' '-DUSE_X11=1' '-DOS_CHROMEOS=1' '-DUSE_XI2_MT=2' '-DFILE_MANAGER_EXTENSION=1' '-DIMAGE_LOADER_EXTENSION=1' '-DENABLE_REMOTING=1' '-DENABLE_WEBRTC=1' '-DENABLE_PEPPER_CDMS' '-DENABLE_CONFIGURATION_POLICY' '-DENABLE_INPUT_SPEECH' '-DENABLE_NOTIFICATIONS' '-DENABLE_HIDPI=1' '-DUSE_UDEV' '-DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC' '-DENABLE_EGLIMAGE=1' '-DENABLE_TASK_MANAGER=1' '-DENABLE_EXTENSIONS=1' '-DENABLE_PLUGINS=1' '-DENABLE_SESSION_SERVICE=1' '-DENABLE_THEMES=1' '-DENABLE_AUTOFILL_DIALOG=1' '-DENABLE_BACKGROUND=1' '-DENABLE_AUTOMATION=1' '-DENABLE_GOOGLE_NOW=1' '-DCLD_VERSION=2' '-DENABLE_FULL_PRINTING=1' '-DENABLE_PRINTING=1' '-DENABLE_SPELLCHECK=1' '-DENABLE_CAPTIVE_PORTAL_DETECTION=1' '-DENABLE_APP_LIST=1' '-DENABLE_MANAGED_USERS=1' '-DENABLE_MDNS=1' '-DNET_IMPLEMENTATION' '-DENABLE_BUILT_IN_DNS' '-DU_USING_ICU_NAMESPACE=0' '-DU_STATIC_IMPLEMENTATION' '-D__STDC_CONSTANT_MACROS' '-D__STDC_FORMAT_MACROS' '-DNDEBUG' '-DNVALGRIND' '-DDYNAMIC_ANNOTATIONS_ENABLED=0' '-D_FORTIFY_SOURCE=2' -I. -Isdch/open-vcdiff/src -Ithird_party/icu/source/i18n -Ithird_party/icu/source/common -Ithird_party/zlib -Ic/Release/obj/gen/net -Inet/third_party/nss/ssl  -Werror -pthread -fno-exceptions -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wno-unused-local-typedefs -pthread -I/build/daisy/usr/include/glib-2.0 -I/build/daisy/usr/lib/glib-2.0/include -I/build/daisy/usr/include/nss -I/build/daisy/usr/include/nspr -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=hard -mthumb --sysroot=/build/daisy/ -O2 -fno-ident -fdata-sections -ffunction-sections -g -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -Wsign-compare -Wno-abi -MMD -MF c/Release/.deps/c/Release/obj.target/net/net/quic/quic_crypto_stream.o.d.raw -pipe -march=armv7-a -mtune=cortex-a15 -mfpu=neon -mfloat-abi=hard -D__google_stl_debug_vector=1 -c -o c/Release/obj.target/net/net/quic/quic_crypto_stream.o net/quic/quic_crypto_stream.cc
chromeos-chrome-34.0.1755.0_alpha-r1: md5.cc: In function 'void base::MD5Final(base::MD5Digest*, char (*)[88])':
chromeos-chrome-34.0.1755.0_alpha-r1: md5.cc:254:33: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
chromeos-chrome-34.0.1755.0_alpha-r1:          ((uint32 *)ctx->in)[ 14 ] = ctx->bits[0];
chromeos-chrome-34.0.1755.0_alpha-r1:                                  ^
chromeos-chrome-34.0.1755.0_alpha-r1: md5.cc:255:33: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
chromeos-chrome-34.0.1755.0_alpha-r1:          ((uint32 *)ctx->in)[ 15 ] = ctx->bits[1];
chromeos-chrome-34.0.1755.0_alpha-r1:                                  ^

on http://build.chromium.org/p/chromium.chromiumos/builders/ChromiumOS%20%28daisy%29/builds/15156/steps/BuildPackages/logs/stdio

(We don't build with type-based alias analysis enabled, so the warning isn't all
that helpful, but the bot is red none the less.)

> Fixes in base for [P]NaCl port of remoting client
> 
> Various minor fixes in base needed for [P]NaCl port of remoting client:
>   - added base_i18n_untrusted target
>   - md5 is included in base_untrusted.
>   - base/metrics is compiled in base_untrusted (src/net depends on it).
>   - enabled PNaCl build of base_untrusted
>   - __builtin_extract_return_addr() is not allowed in PNaCl (validator
>     rejects it).
>   - sys_byteorder.h now works in NaCl.
> 
> BUG=276739
> 
> Review URL: https://codereview.chromium.org/116803005

TBR=sergeyu@chromium.org

Review URL: https://codereview.chromium.org/120463002

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 8855e98440bde10dfb17493d00aa72715ec9971a