Revert 57572 - Remove the default argument from RegKey::Open.
Caused a failure on Windows Chromium Builder (dbg):

...\configuration_policy_provider_win.cc(71) :
error C2660: 'RegKey::Open' : function does not take
2 arguments

BUG=44644
TEST=base_unittests --gtest_filter=RegistryTest.*

Review URL: http://codereview.chromium.org/3205007

TBR=tfarina@chromium.org
Review URL: http://codereview.chromium.org/3211004

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: fb56c27c85e46336d505cf51047345c5389cedba