Mark EventToTypeString with ALLOW_UNUSED to fix the Official gtk build.
It's only used inside an UNSHIPPED_TRACE_EVENT1(), which causes:

../../base/message_loop/message_pump_gtk.cc:17:13: error: unused function 'EventToTypeString' [-Werror,-Wunused-function]

Review URL: https://codereview.chromium.org/131323005

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: fd14f8126d921d85f21960c8a994150343832a57