Remove explicit cast in discardable_memory_mac.
When building this file (with clang) as 64-bit:

base/memory/discardable_memory_mac.cc:100:23: error: reinterpret_cast from
    'unsigned int' to 'vm_address_t' (aka 'unsigned long') is not allowed

vm_address_t is an unsigned int in the 32-bit environment and an unsigned long
in the 64-bit environment.

It is correct to just specify 0 here. 0 (int) will be implicitly converted to
vm_address_t, regardless of what underlying integral type implements it.
Review URL: https://codereview.chromium.org/11896094

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 05f91f300cf25f56657f23bab26d49064b2aa868