Add '-ldl' to Linux targets that use dynamic loader functions.
This fixes compilation errors on Karmic, where dlopen() and friends were undefined:
http://chrome-buildbot.corp.google.com:8016/builders/Chromium%20Linux%20Builder%20(dbg-shlib)/builds/7777/steps/compile/logs/stdio

The missing '-ldl' is papered over on Hardy because pretty much everything
depends on gtk, which brings that in through pkg-config, but pkg-config gtk
no longer includes '-ldl' on Karmic.

Review URL: http://codereview.chromium.org/656014

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 524f1cfdea8f21922f116fbe96dcd0f71663f4dc