Fix compilation error encountered when DEBUG set to 1.
Fails to compiler if DEBUG is set to 1.  If DEBUG is 0 the error is hidden
because LOG_INFO() expands to an empty operation.

Fixes:
  ../../base/android/linker/linker_jni.cc:270:60: error: 'lib_basename' was not declared in this scope

BUG=390618

Review URL: https://codereview.chromium.org/375883002

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 4a7d85d48daf1f392346229c6bface4ab4de12af