Revert "Cleanup: Remove base/file_util.h. Convert remaining references."
Appears this may have led to a broken build:
chrome_webrtc_simulcast_browsertest.cc:6:10: fatal error: 'base/file_util.h' file not found
Reverting on branch only

This reverts commit 6d63c4898c2da5a286d01f80229baeb914f99f18.

Cr-Original-Commit-Position: refs/branch-heads/2157@{#2}
Cr-Original-Branched-From: 9cc636333cf526081f64a315343e9c3b7f396695-refs/heads/master@{#294733}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: bef745b092f87caacae46e52326038ba7b0f955b