Revert 210434 "Revert 210433 "Revert 210423 "base: Make Sequence..."
The SequencedWorkerPool change broke CrOs (daisy) builder due to unused variable:

  threading/sequenced_worker_pool.cc:682:13: error: variable 'shutdown_wait_begin'

reverting until that is fixed.


> Revert 210433 "Revert 210423 "base: Make SequencedWorkerPool iss..."
> 
> Undoing speculative revert. Still failed after revert.
> 
> > Revert 210423 "base: Make SequencedWorkerPool issue globally uni..."
> > 
> > Speculative revert for failing PageCyclerTest.FailProvisionalLoads on
> > linux_clang.
> > 
> > > base: Make SequencedWorkerPool issue globally unique SequenceTokens.
> > > 
> > > SequencedWorkerPool currently issues SequenceTokens out of an internal member counter. This means that two different SequencedWorkerPool instances can issue identical SequenceTokens, which mucks up any attempt to distinguish sequences using only SequenceTokens.
> > > 
> > > This change makes the SequenceTokens issued from an StaticAtomicSequenceNumber, which is globally shared amongst all SequencedWorkerPools.
> > > 
> > > This change also makes the SequencedWorkerPool included in the nacl_untrusted builds, as it is needed for SequenceChecker and WeakPtr to work correctly. It previously was excluded because it used base/metrics. I've #ifdefed the base/metrics usage out for nacl.
> > > 
> > > This issue is a spinoff and pre-requisite of issue 18501008: Make WeakPtr use SequenceChecker instead of ThreadChecker.
> > > 
> > > R=akalin,darin
> > > BUG=165590
> > > 
> > > Review URL: https://chromiumcodereview.appspot.com/18650006
> > 
> > TBR=tommycli@chromium.org
> > 
> > Review URL: https://codereview.chromium.org/18271011
> 
> TBR=scottmg@chromium.org
> 
> Review URL: https://codereview.chromium.org/18242008

TBR=scottmg@chromium.org

Review URL: https://codereview.chromium.org/18861008

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 7ddc08e0882c666ce97ded90dae5133ab0934612