Revert "[Merge to M43] Use StartsWith rather than == to compare BackgroundRendererProcesses experiment group names."
This reverts commit 7b1b2d47eaba129e1bb62f606c65994177318800.

Broke win_stable compile: http://master.chrome.corp.google.com:8011/builders/win%20stable/builds/1746/steps/compile/logs/stdio :

c:\b\build\slave\win_stable\build\src\content\browser\renderer_host\render_process_host_impl.cc(2232) : error C2039: 'StartsWithASCII' : is not a member of 'base'
ninja: build stopped: subcommand failed.

TBR=avi
BUG=501885

Review URL: https://codereview.chromium.org/1211333006.

Cr-Original-Commit-Position: refs/branch-heads/2357@{#490}
Cr-Original-Branched-From: 59d4494849b405682265ed5d3f5164573b9a939b-refs/heads/master@{#323860}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: d10fc1929b8dfe5e7912d292e6f7fe863fc6eb35